-- Missing: Attendance table
CREATE TABLE IF NOT EXISTS `attendance` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `school_id` int unsigned NOT NULL,
  `academic_year_id` int unsigned NOT NULL,
  `class_id` int unsigned NOT NULL,
  `section_id` int unsigned NOT NULL,
  `student_id` int unsigned NOT NULL,
  `attendance_date` date NOT NULL,
  `period_id` int unsigned DEFAULT NULL,
  `subject_id` int unsigned DEFAULT NULL,
  `session_type` enum('morning','evening','period') DEFAULT 'morning',
  `status` enum('present','absent','late','excused','half_day') NOT NULL DEFAULT 'present',
  `remarks` varchar(255) DEFAULT NULL,
  `marked_by` int unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_attendance` (`student_id`,`attendance_date`,`session_type`,`period_id`),
  KEY `school_id` (`school_id`),
  KEY `section_id` (`section_id`),
  KEY `marked_by` (`marked_by`),
  KEY `idx_attendance_date` (`attendance_date`),
  KEY `idx_attendance_class` (`class_id`,`section_id`,`attendance_date`),
  CONSTRAINT `attendance_ibfk_1` FOREIGN KEY (`school_id`) REFERENCES `schools` (`id`) ON DELETE CASCADE,
  CONSTRAINT `attendance_ibfk_2` FOREIGN KEY (`class_id`) REFERENCES `classes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `attendance_ibfk_3` FOREIGN KEY (`section_id`) REFERENCES `sections` (`id`) ON DELETE CASCADE,
  CONSTRAINT `attendance_ibfk_4` FOREIGN KEY (`student_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `attendance_ibfk_5` FOREIGN KEY (`marked_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
